### ISSUE TITLE
유튜브-dl의 마지막 병합과정에서 오류

### ISSUE THREAD

**Issue by devBin28** [tenebo/Hitomi-Downloader-Mac#11]
유튜브 영상과 음원 모두 마지막 병합과정에서 합쳐지지 못하고, 작업 불완전하게 유지되는 현상.
모두 용량은 정상적으로 다운이 되지만, 최종적으로 병합되는 부분에서 오류가 나는 것 같아요.
mac버전에서는 youtube-dl만 손 봐주실 수 있을까요?

**Comment by tenebo** [comment]
I think there was a bug because of the change in Pyinstaller. Please try the newest version. https://github.com/tenebo/Hitomi-Downloader-Mac/releases/tag/v3.8f-0.2
