### ISSUE TITLE
IT occasionally crashes. 

### ISSUE THREAD

**Issue by Starswinds** [tenebo/Hitomi-Downloader-Mac#17]
I don't guess when it happes. I think I occur when a work done.
below is the error report of it

[Error Report.txt](https://github.com/tenebo/Hitomi-Downloader-Mac/files/14034087/Error.Report.txt)

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               hitomi_downloader_GUI [1667]
Path:                  /Applications/hitomi_downloader_GUI.app/Contents/MacOS/hitomi_downloader_GUI
Identifier:            hitomi_downloader_GUI
Version:               0.0.0 (???)
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2024-01-24 15:29:43.0299 +0900
OS Version:            macOS 14.2.1 (23C71)
Report Version:        12
Bridge OS Version:     8.2 (21P2057)
Anonymous UUID:        7BD91BF5-532E-C526-C711-F6CA6AA34241

Sleep/Wake UUID:       F342FE99-DB65-4280-A6E2-8786FC62C0CF

Time Awake Since Boot: 2500 seconds
Time Since Wake:       395 seconds

System Integrity Protection: enabled

Crashed Thread:        101  Thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace SIGNAL, Code 6 Abort trap: 6
Terminating Process:   hitomi_downloader_GUI [1667]

Application Specific Information:
abort() called

Kernel Triage:
VM - (arg = 0x3) mach_vm_allocate_kernel failed within call to vm_map_enter

Thread 101 Crashed:: Thread
0   libsystem_kernel.dylib        	    0x7ff81719f7a2 __pthread_kill + 10
1   libsystem_pthread.dylib       	    0x7ff8171d7f30 pthread_kill + 262
2   libsystem_c.dylib             	    0x7ff8170f6a49 abort + 126
3   QtCore                        	       0x1147c7ef9 qAbort() + 9
4   QtCore                        	       0x1147d00e9 0x1147af000 + 135401
5   QtCore                        	       0x1147cb1d4 0x1147af000 + 115156
6   QtCore                        	       0x114b39488 QMessageLogger::fatal(char const*, ...) const + 122
7   QtCore                        	       0x114b3f78e 0x1147af000 + 3737486
8   QtCore                        	       0x11492305d QThread::~QThread() + 253
9   QtCore.abi3.so                	       0x10d674df7 QThreadWrapper::~QThreadWrapper() + 55
10  libshiboken6.abi3.6.6.dylib   	       0x10983cbd3 SbkDeallocWrapperCommon(_object*, bool) + 291
11  Python3                       	       0x1086d7b87 0x108641000 + 617351
12  Python3                       	       0x108685b5e 0x108641000 + 281438
13  QtCore.abi3.so                	       0x10d6749be QThreadWrapper::run() + 286
14  QtCore                        	       0x1149c5709 0x1147af000 + 2189065
15  libsystem_pthread.dylib       	    0x7ff8171d8202 _pthread_start + 99
16  libsystem_pthread.dylib       	    0x7ff8171d3bab thread_start + 15

Thread 101 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000006  rcx: 0x000070000c958be8  rdx: 0x0000000000000000
  rdi: 0x0000000000024613  rsi: 0x0000000000000006  rbp: 0x000070000c958c10  rsp: 0x000070000c958be8
   r8: 0x00007ff85a801350   r9: 0x00000000ffffff00  r10: 0x0000000000000000  r11: 0x0000000000000246
  r12: 0x0000000000024613  r13: 0x0000000199ab3100  r14: 0x000070000c959000  r15: 0x0000000000000016
  rip: 0x00007ff81719f7a2  rfl: 0x0000000000000246  cr2: 0x0000000000000000
  
Logical CPU:     0
Error Code:      0x02000148 
Trap Number:     133

**Comment by tenebo** [comment]
There was a problem with the thread buffer. Please install latest version.
