### ISSUE TITLE
안녕하세요. 맥os에서 프로그램이 열리지 않습니다. 

### ISSUE THREAD

**Issue by hocheolryu** [tenebo/Hitomi-Downloader-Mac#18]
프로그램은 설치되지만 열리지 않습니다 어떻게 하는 것이 좋을까요? 부탁드립니다

**Comment by smart2k** [comment]
혹시 프로그램 작성자를 확인할 수 없어 설치가 안되는 경우라면 System Settings가셔서 Privacy & Security 들어가보시면 Security에 히토미 다운로더를 실행할꺼냐 물어보고 있는 부분이 있습니다. 거기에서 확인해주시고 비번 입력해주시면 실행됩니다.
그게 아닌 경우라면 어떤 증상을 보이는지 구체적으로 써주셔야이 질문글을 보는 사람들이 도움을 드릴 수 있을 것 같네요

**Comment by tenebo** [comment]
Can you elaborate on the issue you are having? How it is not working?

**Comment by hocheolryu** [comment]
맥 Ios 문제였습니다. 업데이트를 완료하니 해결되었습니다. 
신경써주셔서 감사합니다!
