### ISSUE TITLE
下载后无法打开闪退，m1芯片的mac电脑支持吗？

### ISSUE THREAD

**Issue by li751961845** [tenebo/Hitomi-Downloader-Mac#21]

**Comment by WeiMao33** [comment]
I have the same problem with M1

**Comment by tenebo** [comment]
Please elaborate on the issue you are having. How is it not working?

**Comment by WeiMao33** [comment]
After installation, click and the program will flash back without any error prompts.

**Comment by WeiMao33** [comment]
With the Mac info: MacBook Pro,Apple M1, macOS 12.4 (21F79)

**Comment by tenebo** [comment]
I was not able to replicate the error. Please update the Mac OS to newest version.

**Comment by WeiMao33** [comment]
> I was not able to replicate the error. Please update the Mac OS to newest version.

thanks, I will try it.
