### ISSUE TITLE
DPI 대체안

### ISSUE THREAD

**Issue by shaper12340w** [tenebo/Hitomi-Downloader-Mac#23]
모든 Mac이나 추후 나온다면 Linux에서 작동될지는 모르겠습니다만 다음 라이브러리를 사용해서 GoodbyeDPI 대체안으로 사용하면 좋을듯 합니다. https://github.com/xvzc/SpoofDPI

**Comment by tenebo** [comment]
I don't think It isn't necessary. You can use DPI through the proxy setting.
