### ISSUE TITLE
无法从 YouTube下载视频

### ISSUE THREAD

**Issue by JJHN585858** [tenebo/Hitomi-Downloader-Mac#28]
昨天到今天一直无法下载怎么解决？

**Comment by JJHN585858** [comment]
<img width="451" alt="1721448864391" src="https://github.com/user-attachments/assets/2ffdc2f0-22d6-4e37-b5d5-f66993ae5630">

**Comment by tenebo** [comment]
[duplicate issue](https://github.com/KurtBestor/Hitomi-Downloader/issues/7343)

**Comment by JJHN585858** [comment]
那什么时候可以恢复、

**Comment by JJHN585858** [comment]
> [重复问题](https://github.com/KurtBestor/Hitomi-Downloader/issues/7343)

能不能修复一下啊？
