### ISSUE TITLE
리눅스 지원은 불가능한가요?

### ISSUE THREAD

**Issue by ocformula** [tenebo/Hitomi-Downloader-Mac#3]
맥과 리눅스는 파일 시스템 구조도 거의 동일하고 라이브러리도 윈도우보다는 차이가 덜한걸로 알고있습니다.

**Comment by tenebo** [comment]
I'm building it by using Pyinstaller. Unfortunately, I don't think Pyinstaller supports cross platform building, so there are difficulties to support the Linux version.

**Comment by kimnamwook1** [comment]
It doesnt work in Macbook. why does it happen?

**Comment by tenebo** [comment]
There is a Linux version created by the original author.
https://github.com/KurtBestor/Hitomi-Downloader/issues/3771
