### ISSUE TITLE
DMG FILE SIZE

### ISSUE THREAD

**Issue by notFaad** [tenebo/Hitomi-Downloader-Mac#4]
Why is the .dmg file around 511 mb while the original hitomi is 81 mb?

**Comment by tenebo** [comment]
The Windows Exe file itself is compressed, so it might be much larger including a decompressed temporary file. Also, the Mac version uses PySide instead of PyQt. PySide weighs twice as much as PyQt, which is another reason.

**Comment by notFaad** [comment]
Thanks for the response
