### ISSUE TITLE
Error messages when opening.

### ISSUE THREAD

**Issue by libreidy** [tenebo/Hitomi-Downloader-Mac#6]
It is working fine but when I open the app I get these two errors.

<img width="463" alt="Screenshot 2023-10-03 at 11 42 58 PM" src="https://github.com/tenebo/Hitomi-Downloader-Mac/assets/13302352/6543e0ff-8dd7-44d8-b550-fa49ff2adfa5">

**Comment by tenebo** [comment]
It is an unsupported feature from the windows version. You may ignore that.

**Comment by libreidy** [comment]
Thank you for making this work on the Mac.
