### ISSUE TITLE
Ask for multi-line input

### ISSUE THREAD

**Issue by minyeamer** [tenebo/Hitomi-Downloader-Mac#8]
As a Mac user, thank you for sharing a great program.

I thought that bulk-input is supported in the original Hitomi download,
but this program, when entering multi-line URLs, seems to recognize only the first URL.
Is there a way to enter all URLs for input separated by \n character?

**Comment by tenebo** [comment]
Thank you for your feedback
Please upgrade to the new version or install it from https://github.com/tenebo/Hitomi-Downloader-Mac/releases/tag/v3.8f-0.0-beta.1

**Comment by minyeamer** [comment]
Thank you for your quick upgrade. It works well.
